server:
   port: ${PORT:8861}
message: Configuracion de cliente en el servidor levantado!
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zetazeta?serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
      database-platfomr: org.hibernate.dialect.MySQLDialect
